version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs-typescript
    ports:
      - "3306:3306"
